# These are supported funding model platforms

github: [lwierzbicki] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: v13rsba
custom: ['https://www.buymeacoffee.com/v13rsba'] 
